# Generated by Django 4.2.30 on 2026-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('mixed', 'Mixed')], default='en', max_length=10)),
                ('raw_text', models.TextField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('model_used', models.CharField(choices=[('vsm', 'Vector Space Model (TF-IDF)'), ('bm25', 'BM25')], max_length=10)),
                ('precision_at_5', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('results_json', models.TextField(default='[]')),
                ('relevant_docs_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('doc_frequency', models.IntegerField(default=0)),
                ('postings_json', models.TextField(default='{}')),
            ],
            options={
                'verbose_name_plural': 'Index Entries',
                'ordering': ['term'],
            },
        ),
    ]
