# Generated by Django 5.2.14 on 2026-05-26 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_document_owner_document_status_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=500, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SpellCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misspelled', models.CharField(db_index=True, max_length=200, unique=True)),
                ('corrected', models.CharField(max_length=200)),
                ('frequency', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-frequency'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA256 checksum for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_indexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='f1_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='mean_average_precision',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indexentry',
            name='idf_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='indexentry',
            name='total_term_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='model_used',
            field=models.CharField(default='vsm', max_length=10),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='results_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_indexed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('am', 'Amharic'), ('mixed', 'Mixed')], db_index=True, default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query_text',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'is_indexed'], name='search_docu_status_1d2659_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['language', 'status'], name='search_docu_languag_a7145c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='search_docu_created_239df0_idx'),
        ),
        migrations.AddIndex(
            model_name='indexentry',
            index=models.Index(fields=['term'], name='search_inde_term_6b5e07_idx'),
        ),
        migrations.AddIndex(
            model_name='indexentry',
            index=models.Index(fields=['doc_frequency'], name='search_inde_doc_fre_43b17c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', '-timestamp'], name='search_sear_user_id_3d39e3_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query_text'], name='search_sear_query_t_c84f03_idx'),
        ),
        migrations.AddIndex(
            model_name='querysuggestion',
            index=models.Index(fields=['-search_count', '-last_searched'], name='search_quer_search__a30812_idx'),
        ),
    ]
